--------------------------------------------------------
--  File created - Wednesday-May-03-2023   
--------------------------------------------------------
REM INSERTING into ALPHA.T_BARAA
SET DEFINE OFF;
REM INSERTING into ALPHA.T_BARAA_TURUL
SET DEFINE OFF;
Insert into ALPHA.T_BARAA_TURUL (ID,NME,SRT,DELETED,SYNCED) values ('pivo','Пиво',1,'0','0');
Insert into ALPHA.T_BARAA_TURUL (ID,NME,SRT,DELETED,SYNCED) values ('arhi','Архи',2,'0','0');
Insert into ALPHA.T_BARAA_TURUL (ID,NME,SRT,DELETED,SYNCED) values ('undaa','Ундаа',3,'0','0');
Insert into ALPHA.T_BARAA_TURUL (ID,NME,SRT,DELETED,SYNCED) values ('zuush','Зууш',4,'0','0');
Insert into ALPHA.T_BARAA_TURUL (ID,NME,SRT,DELETED,SYNCED) values ('shul','Шөл',5,'0','0');
Insert into ALPHA.T_BARAA_TURUL (ID,NME,SRT,DELETED,SYNCED) values ('hool','Хоол',6,'0','0');
Insert into ALPHA.T_BARAA_TURUL (ID,NME,SRT,DELETED,SYNCED) values ('kocktail','Коктэйл',7,'0','0');
Insert into ALPHA.T_BARAA_TURUL (ID,NME,SRT,DELETED,SYNCED) values ('wine','Wine',8,'0','0');
Insert into ALPHA.T_BARAA_TURUL (ID,NME,SRT,DELETED,SYNCED) values ('whisky','Whisky',9,'0','0');
Insert into ALPHA.T_BARAA_TURUL (ID,NME,SRT,DELETED,SYNCED) values ('dessert','Dessert',10,'0','0');
Insert into ALPHA.T_BARAA_TURUL (ID,NME,SRT,DELETED,SYNCED) values ('total','Бүгд',0,'0','0');
REM INSERTING into ALPHA.T_BELL
SET DEFINE OFF;
REM INSERTING into ALPHA.T_HURUNGU
SET DEFINE OFF;
REM INSERTING into ALPHA.T_LOGS
SET DEFINE OFF;
REM INSERTING into ALPHA.T_MESSAGES
SET DEFINE OFF;
Insert into ALPHA.T_MESSAGES (CODE,NAME,BACKEND,URL,BODY_TEMPLATE,CREATED_DATE,METHOD,IS_PROTECTED,IS_END,SKIP_LOG,DELETED,SYNCED) values (100000,'Login user','GLBL_BACKEND','{}','{}',to_date('23-DEC-21','DD-MON-RR'),'{}','N','Y',0,'0','0');
Insert into ALPHA.T_MESSAGES (CODE,NAME,BACKEND,URL,BODY_TEMPLATE,CREATED_DATE,METHOD,IS_PROTECTED,IS_END,SKIP_LOG,DELETED,SYNCED) values (104000,'crime report select','GLBL_BACKEND','{}','{}',to_date('15-FEB-22','DD-MON-RR'),null,'N','Y',0,'0','0');
Insert into ALPHA.T_MESSAGES (CODE,NAME,BACKEND,URL,BODY_TEMPLATE,CREATED_DATE,METHOD,IS_PROTECTED,IS_END,SKIP_LOG,DELETED,SYNCED) values (102003,'Legal Delete','GLBL_BACKEND','{}','{}',to_date('25-JAN-22','DD-MON-RR'),null,'N','Y',0,'0','0');
Insert into ALPHA.T_MESSAGES (CODE,NAME,BACKEND,URL,BODY_TEMPLATE,CREATED_DATE,METHOD,IS_PROTECTED,IS_END,SKIP_LOG,DELETED,SYNCED) values (104001,'Crime Report Insert Or update','GLBL_BACKEND',null,null,to_date('15-FEB-22','DD-MON-RR'),null,'N','Y',0,'0','0');
Insert into ALPHA.T_MESSAGES (CODE,NAME,BACKEND,URL,BODY_TEMPLATE,CREATED_DATE,METHOD,IS_PROTECTED,IS_END,SKIP_LOG,DELETED,SYNCED) values (104003,'Crime Report Delete','GLBL_BACKEND','{}','{}',to_date('15-FEB-22','DD-MON-RR'),null,'N','Y',0,'0','0');
Insert into ALPHA.T_MESSAGES (CODE,NAME,BACKEND,URL,BODY_TEMPLATE,CREATED_DATE,METHOD,IS_PROTECTED,IS_END,SKIP_LOG,DELETED,SYNCED) values (100002,'Change password','GLBL_BACKEND','{}','{}',to_date('04-MAR-22','DD-MON-RR'),null,'N','Y',0,'0','0');
Insert into ALPHA.T_MESSAGES (CODE,NAME,BACKEND,URL,BODY_TEMPLATE,CREATED_DATE,METHOD,IS_PROTECTED,IS_END,SKIP_LOG,DELETED,SYNCED) values (105000,'Crime Worker','GLBL_BACKEND',null,null,to_date('15-FEB-22','DD-MON-RR'),null,'N','Y',0,'0','0');
Insert into ALPHA.T_MESSAGES (CODE,NAME,BACKEND,URL,BODY_TEMPLATE,CREATED_DATE,METHOD,IS_PROTECTED,IS_END,SKIP_LOG,DELETED,SYNCED) values (105001,'Crime Worker insert','GLBL_BACKEND',null,null,to_date('15-FEB-22','DD-MON-RR'),null,'N','Y',0,'0','0');
Insert into ALPHA.T_MESSAGES (CODE,NAME,BACKEND,URL,BODY_TEMPLATE,CREATED_DATE,METHOD,IS_PROTECTED,IS_END,SKIP_LOG,DELETED,SYNCED) values (105003,'Crime Worker Delete','GLBL_BACKEND',null,null,to_date('15-FEB-22','DD-MON-RR'),null,'N','Y',0,'0','0');
Insert into ALPHA.T_MESSAGES (CODE,NAME,BACKEND,URL,BODY_TEMPLATE,CREATED_DATE,METHOD,IS_PROTECTED,IS_END,SKIP_LOG,DELETED,SYNCED) values (102005,'Legal Report','GLBL_BACKEND','{}','{}',to_date('21-JAN-22','DD-MON-RR'),null,'N','Y',0,'0','0');
Insert into ALPHA.T_MESSAGES (CODE,NAME,BACKEND,URL,BODY_TEMPLATE,CREATED_DATE,METHOD,IS_PROTECTED,IS_END,SKIP_LOG,DELETED,SYNCED) values (102006,'Test Legal','GLBL_BACKEND','{}','{}',to_date('21-JAN-22','DD-MON-RR'),null,'N','Y',0,'0','0');
Insert into ALPHA.T_MESSAGES (CODE,NAME,BACKEND,URL,BODY_TEMPLATE,CREATED_DATE,METHOD,IS_PROTECTED,IS_END,SKIP_LOG,DELETED,SYNCED) values (103002,'Crime Update','GLBL_BACKEND',null,null,to_date('26-JAN-22','DD-MON-RR'),null,'N','Y',0,'0','0');
Insert into ALPHA.T_MESSAGES (CODE,NAME,BACKEND,URL,BODY_TEMPLATE,CREATED_DATE,METHOD,IS_PROTECTED,IS_END,SKIP_LOG,DELETED,SYNCED) values (103000,'Crime Select','GLBL_BACKEND','{}','{}',to_date('26-JAN-22','DD-MON-RR'),null,'N','Y',0,'0','0');
Insert into ALPHA.T_MESSAGES (CODE,NAME,BACKEND,URL,BODY_TEMPLATE,CREATED_DATE,METHOD,IS_PROTECTED,IS_END,SKIP_LOG,DELETED,SYNCED) values (103001,'Crime Insert','GLBL_BACKEND','{}','{}',to_date('26-JAN-22','DD-MON-RR'),null,'N','Y',0,'0','0');
Insert into ALPHA.T_MESSAGES (CODE,NAME,BACKEND,URL,BODY_TEMPLATE,CREATED_DATE,METHOD,IS_PROTECTED,IS_END,SKIP_LOG,DELETED,SYNCED) values (103003,'Crime Delete','GLBL_BACKEND',null,null,to_date('26-JAN-22','DD-MON-RR'),null,'N','Y',0,'0','0');
Insert into ALPHA.T_MESSAGES (CODE,NAME,BACKEND,URL,BODY_TEMPLATE,CREATED_DATE,METHOD,IS_PROTECTED,IS_END,SKIP_LOG,DELETED,SYNCED) values (200001,'User create or update','GLBL_BACKEND',null,null,to_date('28-FEB-22','DD-MON-RR'),null,'N','Y',0,'0','0');
Insert into ALPHA.T_MESSAGES (CODE,NAME,BACKEND,URL,BODY_TEMPLATE,CREATED_DATE,METHOD,IS_PROTECTED,IS_END,SKIP_LOG,DELETED,SYNCED) values (200000,'User select','GLBL_BACKEND',null,null,to_date('28-FEB-22','DD-MON-RR'),null,'N','Y',0,'0','0');
Insert into ALPHA.T_MESSAGES (CODE,NAME,BACKEND,URL,BODY_TEMPLATE,CREATED_DATE,METHOD,IS_PROTECTED,IS_END,SKIP_LOG,DELETED,SYNCED) values (200003,'user delete','GLBL_BACKEND',null,null,to_date('28-FEB-22','DD-MON-RR'),null,'N','Y',0,'0','0');
Insert into ALPHA.T_MESSAGES (CODE,NAME,BACKEND,URL,BODY_TEMPLATE,CREATED_DATE,METHOD,IS_PROTECTED,IS_END,SKIP_LOG,DELETED,SYNCED) values (110004,'Get task by id','GLBL_BACKEND','{}','{}',to_date('09-MAR-22','DD-MON-RR'),null,'N','Y',0,'0','0');
Insert into ALPHA.T_MESSAGES (CODE,NAME,BACKEND,URL,BODY_TEMPLATE,CREATED_DATE,METHOD,IS_PROTECTED,IS_END,SKIP_LOG,DELETED,SYNCED) values (101000,'Legal type','GLBL_BACKEND','{}','{}',to_date('11-JAN-22','DD-MON-RR'),'{}','N','Y',0,'0','0');
Insert into ALPHA.T_MESSAGES (CODE,NAME,BACKEND,URL,BODY_TEMPLATE,CREATED_DATE,METHOD,IS_PROTECTED,IS_END,SKIP_LOG,DELETED,SYNCED) values (102001,'Legal Insert','GLBL_BACKEND','{}','{}',to_date('18-JAN-22','DD-MON-RR'),null,'N','Y',0,'0','0');
Insert into ALPHA.T_MESSAGES (CODE,NAME,BACKEND,URL,BODY_TEMPLATE,CREATED_DATE,METHOD,IS_PROTECTED,IS_END,SKIP_LOG,DELETED,SYNCED) values (110005,'Update task details','GLBL_BACKEND','{}','{}',to_date('10-MAR-22','DD-MON-RR'),null,'N','Y',0,'0','0');
Insert into ALPHA.T_MESSAGES (CODE,NAME,BACKEND,URL,BODY_TEMPLATE,CREATED_DATE,METHOD,IS_PROTECTED,IS_END,SKIP_LOG,DELETED,SYNCED) values (110001,'Insert Task','GLBL_BACKEND','{}','{}',to_date('17-FEB-22','DD-MON-RR'),null,'N','Y',0,'0','0');
Insert into ALPHA.T_MESSAGES (CODE,NAME,BACKEND,URL,BODY_TEMPLATE,CREATED_DATE,METHOD,IS_PROTECTED,IS_END,SKIP_LOG,DELETED,SYNCED) values (110003,'Delete Task','GLBL_BACKEND',null,null,to_date('17-FEB-22','DD-MON-RR'),null,'N','Y',0,'0','0');
Insert into ALPHA.T_MESSAGES (CODE,NAME,BACKEND,URL,BODY_TEMPLATE,CREATED_DATE,METHOD,IS_PROTECTED,IS_END,SKIP_LOG,DELETED,SYNCED) values (110000,'Task','GLBL_BACKEND',null,null,to_date('17-FEB-22','DD-MON-RR'),null,'N','Y',0,'0','0');
Insert into ALPHA.T_MESSAGES (CODE,NAME,BACKEND,URL,BODY_TEMPLATE,CREATED_DATE,METHOD,IS_PROTECTED,IS_END,SKIP_LOG,DELETED,SYNCED) values (100001,'chooser','GLBL_BACKEND','{}','{}',to_date('23-DEC-21','DD-MON-RR'),'{}','N','Y',0,'0','0');
Insert into ALPHA.T_MESSAGES (CODE,NAME,BACKEND,URL,BODY_TEMPLATE,CREATED_DATE,METHOD,IS_PROTECTED,IS_END,SKIP_LOG,DELETED,SYNCED) values (123003,'delete shiree','GLBL_BACKEND','{}','{}',to_date('23-DEC-21','DD-MON-RR'),'{}','N','Y',0,'0','0');
Insert into ALPHA.T_MESSAGES (CODE,NAME,BACKEND,URL,BODY_TEMPLATE,CREATED_DATE,METHOD,IS_PROTECTED,IS_END,SKIP_LOG,DELETED,SYNCED) values (124000,'f get shiree','GLBL_BACKEND','{}','{}',to_date('23-DEC-21','DD-MON-RR'),'{}','N','Y',0,'0','0');
Insert into ALPHA.T_MESSAGES (CODE,NAME,BACKEND,URL,BODY_TEMPLATE,CREATED_DATE,METHOD,IS_PROTECTED,IS_END,SKIP_LOG,DELETED,SYNCED) values (124003,'delete baraa','GLBL_BACKEND','{}','{}',to_date('23-DEC-21','DD-MON-RR'),'{}','N','Y',0,'0','0');
Insert into ALPHA.T_MESSAGES (CODE,NAME,BACKEND,URL,BODY_TEMPLATE,CREATED_DATE,METHOD,IS_PROTECTED,IS_END,SKIP_LOG,DELETED,SYNCED) values (123000,'f get shiree','GLBL_BACKEND','{}','{}',to_date('23-DEC-21','DD-MON-RR'),'{}','Y','Y',0,'0','0');
Insert into ALPHA.T_MESSAGES (CODE,NAME,BACKEND,URL,BODY_TEMPLATE,CREATED_DATE,METHOD,IS_PROTECTED,IS_END,SKIP_LOG,DELETED,SYNCED) values (123001,'insert update shiree','GLBL_BACKEND','{}','{}',to_date('23-DEC-21','DD-MON-RR'),'{}','N','Y',0,'0','0');
Insert into ALPHA.T_MESSAGES (CODE,NAME,BACKEND,URL,BODY_TEMPLATE,CREATED_DATE,METHOD,IS_PROTECTED,IS_END,SKIP_LOG,DELETED,SYNCED) values (124001,'insert update shiree','GLBL_BACKEND','{}','{}',to_date('23-DEC-21','DD-MON-RR'),'{}','N','Y',0,'0','0');
Insert into ALPHA.T_MESSAGES (CODE,NAME,BACKEND,URL,BODY_TEMPLATE,CREATED_DATE,METHOD,IS_PROTECTED,IS_END,SKIP_LOG,DELETED,SYNCED) values (128000,'Uldegdel','GLBL_BACKEND','{}','{}',to_date('28-APR-23','DD-MON-RR'),'{}','N','Y',0,'0','0');
Insert into ALPHA.T_MESSAGES (CODE,NAME,BACKEND,URL,BODY_TEMPLATE,CREATED_DATE,METHOD,IS_PROTECTED,IS_END,SKIP_LOG,DELETED,SYNCED) values (125001,'insert order','GLBL_BACKEND','{}','{}',to_date('28-APR-23','DD-MON-RR'),'{}','N','Y',0,'0','0');
Insert into ALPHA.T_MESSAGES (CODE,NAME,BACKEND,URL,BODY_TEMPLATE,CREATED_DATE,METHOD,IS_PROTECTED,IS_END,SKIP_LOG,DELETED,SYNCED) values (126001,'insert orlogo','GLBL_BACKEND','{}','{}',to_date('28-APR-23','DD-MON-RR'),'{}','N','Y',0,'0','0');
Insert into ALPHA.T_MESSAGES (CODE,NAME,BACKEND,URL,BODY_TEMPLATE,CREATED_DATE,METHOD,IS_PROTECTED,IS_END,SKIP_LOG,DELETED,SYNCED) values (127000,'Huulga','GLBL_BACKEND','{}','{}',to_date('28-APR-23','DD-MON-RR'),'{}','N','Y',0,'0','0');
Insert into ALPHA.T_MESSAGES (CODE,NAME,BACKEND,URL,BODY_TEMPLATE,CREATED_DATE,METHOD,IS_PROTECTED,IS_END,SKIP_LOG,DELETED,SYNCED) values (190001,'insert bell notification','GLBL_BACKEND','{}','{}',to_date('23-DEC-21','DD-MON-RR'),'{}','N','Y',1,'0','0');
Insert into ALPHA.T_MESSAGES (CODE,NAME,BACKEND,URL,BODY_TEMPLATE,CREATED_DATE,METHOD,IS_PROTECTED,IS_END,SKIP_LOG,DELETED,SYNCED) values (190000,'get bell data','GLBL_BACKEND','{}','{}',to_date('23-DEC-21','DD-MON-RR'),'{}','N','Y',1,'0','0');
Insert into ALPHA.T_MESSAGES (CODE,NAME,BACKEND,URL,BODY_TEMPLATE,CREATED_DATE,METHOD,IS_PROTECTED,IS_END,SKIP_LOG,DELETED,SYNCED) values (124009,'f get data','GLBL_BACKEND','{}','{}',to_date('23-DEC-21','DD-MON-RR'),'{}','N','Y',1,'0','0');
REM INSERTING into ALPHA.T_ORDER
SET DEFINE OFF;
REM INSERTING into ALPHA.T_PENDINGS
SET DEFINE OFF;
REM INSERTING into ALPHA.T_PRODUCTBALANCE
SET DEFINE OFF;
REM INSERTING into ALPHA.T_RESPONSE_MESSAGES
SET DEFINE OFF;
Insert into ALPHA.T_RESPONSE_MESSAGES (ID,LANGUAGE_CODE,MESSAGE_CODE,CONTENT,CREATED_DATE,UPDATED_DATE,DELETED,SYNCED) values (1,'MN','success','Амжилттай',to_date('15-DEC-20','DD-MON-RR'),to_date('15-DEC-20','DD-MON-RR'),'0','0');
Insert into ALPHA.T_RESPONSE_MESSAGES (ID,LANGUAGE_CODE,MESSAGE_CODE,CONTENT,CREATED_DATE,UPDATED_DATE,DELETED,SYNCED) values (2,'MN','error_request','Алдаатай хүсэлт',to_date('15-DEC-20','DD-MON-RR'),to_date('15-DEC-20','DD-MON-RR'),'0','0');
Insert into ALPHA.T_RESPONSE_MESSAGES (ID,LANGUAGE_CODE,MESSAGE_CODE,CONTENT,CREATED_DATE,UPDATED_DATE,DELETED,SYNCED) values (3,'MN','not_found','Үр дүн олдсонгүй',to_date('15-DEC-20','DD-MON-RR'),to_date('15-DEC-20','DD-MON-RR'),'0','0');
Insert into ALPHA.T_RESPONSE_MESSAGES (ID,LANGUAGE_CODE,MESSAGE_CODE,CONTENT,CREATED_DATE,UPDATED_DATE,DELETED,SYNCED) values (4,'MN','forbidden','Хандах эрхгүй байна',to_date('15-DEC-20','DD-MON-RR'),to_date('15-DEC-20','DD-MON-RR'),'0','0');
Insert into ALPHA.T_RESPONSE_MESSAGES (ID,LANGUAGE_CODE,MESSAGE_CODE,CONTENT,CREATED_DATE,UPDATED_DATE,DELETED,SYNCED) values (5,'MN','internal_error','Дотоод кодын алдаа',to_date('15-DEC-20','DD-MON-RR'),to_date('15-DEC-20','DD-MON-RR'),'0','0');
Insert into ALPHA.T_RESPONSE_MESSAGES (ID,LANGUAGE_CODE,MESSAGE_CODE,CONTENT,CREATED_DATE,UPDATED_DATE,DELETED,SYNCED) values (6,'MN','sent_otp','Баталгаажуулах код илгээлээ.',to_date('15-DEC-20','DD-MON-RR'),to_date('15-DEC-20','DD-MON-RR'),'0','0');
Insert into ALPHA.T_RESPONSE_MESSAGES (ID,LANGUAGE_CODE,MESSAGE_CODE,CONTENT,CREATED_DATE,UPDATED_DATE,DELETED,SYNCED) values (7,'MN','device_not_registered','Бүртгэлгүй төхөөрөмж байна.',to_date('15-DEC-20','DD-MON-RR'),to_date('15-DEC-20','DD-MON-RR'),'0','0');
Insert into ALPHA.T_RESPONSE_MESSAGES (ID,LANGUAGE_CODE,MESSAGE_CODE,CONTENT,CREATED_DATE,UPDATED_DATE,DELETED,SYNCED) values (8,'MN','influence_funds','Дансны үлдэгдэл хүрэлцэхгүй байна.',to_date('15-DEC-20','DD-MON-RR'),to_date('15-DEC-20','DD-MON-RR'),'0','0');
Insert into ALPHA.T_RESPONSE_MESSAGES (ID,LANGUAGE_CODE,MESSAGE_CODE,CONTENT,CREATED_DATE,UPDATED_DATE,DELETED,SYNCED) values (9,'MN','incorrect_password','Нууц үг буруу байна.',to_date('15-DEC-20','DD-MON-RR'),to_date('15-DEC-20','DD-MON-RR'),'0','0');
Insert into ALPHA.T_RESPONSE_MESSAGES (ID,LANGUAGE_CODE,MESSAGE_CODE,CONTENT,CREATED_DATE,UPDATED_DATE,DELETED,SYNCED) values (10,'MN','building_not_found','Барилга олдсонгүй.',to_date('15-DEC-20','DD-MON-RR'),to_date('15-DEC-20','DD-MON-RR'),'0','0');
Insert into ALPHA.T_RESPONSE_MESSAGES (ID,LANGUAGE_CODE,MESSAGE_CODE,CONTENT,CREATED_DATE,UPDATED_DATE,DELETED,SYNCED) values (11,'MN','organization_not_found','Байгууллага олдсонгүй.',to_date('15-DEC-20','DD-MON-RR'),to_date('15-DEC-20','DD-MON-RR'),'0','0');
Insert into ALPHA.T_RESPONSE_MESSAGES (ID,LANGUAGE_CODE,MESSAGE_CODE,CONTENT,CREATED_DATE,UPDATED_DATE,DELETED,SYNCED) values (12,'MN','emp_position_not_found','EMP_POSITION олдсонгүй.',to_date('15-DEC-20','DD-MON-RR'),to_date('15-DEC-20','DD-MON-RR'),'0','0');
Insert into ALPHA.T_RESPONSE_MESSAGES (ID,LANGUAGE_CODE,MESSAGE_CODE,CONTENT,CREATED_DATE,UPDATED_DATE,DELETED,SYNCED) values (13,'MN','user_not_found','Хэрэглэгч олдсонгүй.',to_date('15-DEC-20','DD-MON-RR'),to_date('15-DEC-20','DD-MON-RR'),'0','0');
Insert into ALPHA.T_RESPONSE_MESSAGES (ID,LANGUAGE_CODE,MESSAGE_CODE,CONTENT,CREATED_DATE,UPDATED_DATE,DELETED,SYNCED) values (14,'MN','organization_position_not_found','organization_position олдсонгүй',to_date('15-DEC-20','DD-MON-RR'),to_date('15-DEC-20','DD-MON-RR'),'0','0');
Insert into ALPHA.T_RESPONSE_MESSAGES (ID,LANGUAGE_CODE,MESSAGE_CODE,CONTENT,CREATED_DATE,UPDATED_DATE,DELETED,SYNCED) values (15,'MN','organization_position_exceeded','тухайн мэргэжил дээр хүн ажиллаж байна.',to_date('15-DEC-20','DD-MON-RR'),to_date('15-DEC-20','DD-MON-RR'),'0','0');
Insert into ALPHA.T_RESPONSE_MESSAGES (ID,LANGUAGE_CODE,MESSAGE_CODE,CONTENT,CREATED_DATE,UPDATED_DATE,DELETED,SYNCED) values (16,'MN','user_position_exceeded','хэрэглэгч өөр мэргэжил дээр бүртгэлтэй байна.',to_date('15-DEC-20','DD-MON-RR'),to_date('15-DEC-20','DD-MON-RR'),'0','0');
Insert into ALPHA.T_RESPONSE_MESSAGES (ID,LANGUAGE_CODE,MESSAGE_CODE,CONTENT,CREATED_DATE,UPDATED_DATE,DELETED,SYNCED) values (17,'MN','building_not_found','Барилга олдсонгүй.',to_date('15-DEC-20','DD-MON-RR'),to_date('15-DEC-20','DD-MON-RR'),'0','0');
Insert into ALPHA.T_RESPONSE_MESSAGES (ID,LANGUAGE_CODE,MESSAGE_CODE,CONTENT,CREATED_DATE,UPDATED_DATE,DELETED,SYNCED) values (18,'MN','terminal_not_found','Терминал олдсонгүй.',to_date('15-DEC-20','DD-MON-RR'),to_date('15-DEC-20','DD-MON-RR'),'0','0');
Insert into ALPHA.T_RESPONSE_MESSAGES (ID,LANGUAGE_CODE,MESSAGE_CODE,CONTENT,CREATED_DATE,UPDATED_DATE,DELETED,SYNCED) values (19,'MN','gate_not_found','Гарц олдсонгүй.',to_date('15-DEC-20','DD-MON-RR'),to_date('15-DEC-20','DD-MON-RR'),'0','0');
Insert into ALPHA.T_RESPONSE_MESSAGES (ID,LANGUAGE_CODE,MESSAGE_CODE,CONTENT,CREATED_DATE,UPDATED_DATE,DELETED,SYNCED) values (20,'MN','gate_terminal_exceeded','Терминал өөр гарц дээр бүртгэлтэй байна.',to_date('15-DEC-20','DD-MON-RR'),to_date('15-DEC-20','DD-MON-RR'),'0','0');
Insert into ALPHA.T_RESPONSE_MESSAGES (ID,LANGUAGE_CODE,MESSAGE_CODE,CONTENT,CREATED_DATE,UPDATED_DATE,DELETED,SYNCED) values (21,'MN','time_format_error','Цагийн форматын алдаа.',to_date('15-DEC-20','DD-MON-RR'),to_date('15-DEC-20','DD-MON-RR'),'0','0');
Insert into ALPHA.T_RESPONSE_MESSAGES (ID,LANGUAGE_CODE,MESSAGE_CODE,CONTENT,CREATED_DATE,UPDATED_DATE,DELETED,SYNCED) values (22,'MN','org_user_not_found','Ажилтны бүртгэл олдсонгүй.',to_date('15-DEC-20','DD-MON-RR'),to_date('15-DEC-20','DD-MON-RR'),'0','0');
Insert into ALPHA.T_RESPONSE_MESSAGES (ID,LANGUAGE_CODE,MESSAGE_CODE,CONTENT,CREATED_DATE,UPDATED_DATE,DELETED,SYNCED) values (24,'MN','unique_data','Хэрэглэгчийн нэр бүртгэгдсэн байна',to_date('28-FEB-22','DD-MON-RR'),to_date('28-FEB-22','DD-MON-RR'),'0','0');
Insert into ALPHA.T_RESPONSE_MESSAGES (ID,LANGUAGE_CODE,MESSAGE_CODE,CONTENT,CREATED_DATE,UPDATED_DATE,DELETED,SYNCED) values (23,'MN','token_expired','Токены хугацаа дууссан байна',to_date('20-JAN-22','DD-MON-RR'),to_date('20-JAN-22','DD-MON-RR'),'0','0');
REM INSERTING into ALPHA.T_SHIREE
SET DEFINE OFF;
REM INSERTING into ALPHA.T_TEMP
SET DEFINE OFF;
REM INSERTING into ALPHA.T_USERS
SET DEFINE OFF;
Insert into ALPHA.T_USERS (ID,REG_NO,FNM,LNM,FAMILY_NAME,CIVIL_ID,PHONE,UNM,BKD,PASSCODE,BIRTH_DATE,GENDER,EMAIL,ADDRESS,AIMAG_CODE,SUM_CODE,BAG_CODE,ACCOUNT_NO,STATUS,C_LEVEL,IS_CHILD,MOTHER_ID,FATHER_ID,DRIVE_EXP,ZIPCODE,AIMAG_ZIP,SUM_ZIP,CREATED_DATE,DRIVER_LICENSE_NUMBER,PROFILE_IMAGE_URL,DRIVER_LICENSE_NUMBER1,IS_PIN,IS_PHONE_ACTIVATED,IS_EMAIL_ACTIVATED,COUNTRY_CODE,COUNTRY_NAME,CHECKID,RLE,SQD,RNK,STS,PHT,CDT,USR,TOKEN,EXPIREDATE,PASSWORD,NAME,DELETED,SYNCED) values ('3E78C30A239149569D8A818715ACBB8D','ЙН91010914','Нарангэрэл','Саран',null,null,'99886117','admin',null,null,null,null,null,null,null,null,null,null,'A',1,'N',null,null,1,'11000','11000','11000',to_date('01-APR-23','DD-MON-RR'),null,null,null,0,0,0,'MN','Монгол улс',null,'hcr','Пааб',null,'act',null,'2023/04/01',null,'D7BA4AC8956F4F818493CD4C456EC775',to_date('11-AUG-23','DD-MON-RR'),'admins','Нарангэрэл.С','0','0');
