--------------------------------------------------------
--  File created - Wednesday-May-03-2023   
--------------------------------------------------------
DROP TABLE "ALPHA"."T_BARAA" cascade constraints;
DROP TABLE "ALPHA"."T_BARAA_TURUL" cascade constraints;
DROP TABLE "ALPHA"."T_BELL" cascade constraints;
DROP TABLE "ALPHA"."T_HURUNGU" cascade constraints;
DROP TABLE "ALPHA"."T_LOGS" cascade constraints;
DROP TABLE "ALPHA"."T_MESSAGES" cascade constraints;
DROP TABLE "ALPHA"."T_ORDER" cascade constraints;
DROP TABLE "ALPHA"."T_PENDINGS" cascade constraints;
DROP TABLE "ALPHA"."T_PRODUCTBALANCE" cascade constraints;
DROP TABLE "ALPHA"."T_RESPONSE_MESSAGES" cascade constraints;
DROP TABLE "ALPHA"."T_SHIREE" cascade constraints;
DROP TABLE "ALPHA"."T_TEMP" cascade constraints;
DROP TABLE "ALPHA"."T_USERS" cascade constraints;
--------------------------------------------------------
--  DDL for Table T_BARAA
--------------------------------------------------------

  CREATE TABLE "ALPHA"."T_BARAA" 
   (	"ID" VARCHAR2(32 BYTE) DEFAULT sys_guid(), 
	"TRL" VARCHAR2(32 BYTE), 
	"NME" VARCHAR2(100 BYTE), 
	"PHT" CLOB, 
	"NGJ" VARCHAR2(255 BYTE), 
	"JIN" VARCHAR2(244 BYTE), 
	"USR" VARCHAR2(255 BYTE), 
	"STS" VARCHAR2(32 BYTE) DEFAULT 'Идэвхтэй', 
	"CDT" VARCHAR2(32 BYTE) DEFAULT TO_CHAR(sysdate, 'YYYY/MM/DD HH24:MI:SS'), 
	"TRLN" VARCHAR2(32 BYTE), 
	"UNE" VARCHAR2(32 BYTE), 
	"URTUG" VARCHAR2(32 BYTE), 
	"SRT" NUMBER DEFAULT 0, 
	"DELETED" VARCHAR2(2 BYTE) DEFAULT '0', 
	"SYNCED" VARCHAR2(2 BYTE) DEFAULT '0'
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" 
 LOB ("PHT") STORE AS SECUREFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
  STORAGE(INITIAL 106496 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
--------------------------------------------------------
--  DDL for Table T_BARAA_TURUL
--------------------------------------------------------

  CREATE TABLE "ALPHA"."T_BARAA_TURUL" 
   (	"ID" VARCHAR2(32 BYTE) DEFAULT sys_guid(), 
	"NME" VARCHAR2(100 BYTE), 
	"PHT" CLOB, 
	"SRT" NUMBER, 
	"DELETED" VARCHAR2(2 BYTE) DEFAULT '0', 
	"SYNCED" VARCHAR2(2 BYTE) DEFAULT '0'
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" 
 LOB ("PHT") STORE AS SECUREFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
  STORAGE(INITIAL 106496 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
--------------------------------------------------------
--  DDL for Table T_BELL
--------------------------------------------------------

  CREATE TABLE "ALPHA"."T_BELL" 
   (	"ID" VARCHAR2(32 BYTE) DEFAULT sys_guid(), 
	"TABLEID" VARCHAR2(255 BYTE), 
	"TABLENAME" VARCHAR2(255 BYTE), 
	"CREATEDDATE" VARCHAR2(255 BYTE) DEFAULT TO_CHAR(sysdate, 'YYYY-MM-DD HH24:MI:SS'), 
	"DELETED" VARCHAR2(2 BYTE) DEFAULT '0', 
	"SYNCED" VARCHAR2(2 BYTE) DEFAULT '0'
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table T_HURUNGU
--------------------------------------------------------

  CREATE TABLE "ALPHA"."T_HURUNGU" 
   (	"ID" VARCHAR2(32 BYTE) DEFAULT sys_guid(), 
	"NAME" VARCHAR2(255 BYTE), 
	"PHOTO" CLOB, 
	"UNE" VARCHAR2(255 BYTE), 
	"TOO" VARCHAR2(255 BYTE), 
	"EZENID" VARCHAR2(32 BYTE), 
	"STATUS" VARCHAR2(100 BYTE) DEFAULT 'Ашиглалтад', 
	"EZENNAME" VARCHAR2(255 BYTE), 
	"CDT" VARCHAR2(32 BYTE) DEFAULT TO_CHAR(sysdate, 'YYYY/MM/DD HH24:MI:SS'), 
	"USR" VARCHAR2(255 BYTE), 
	"DELETED" VARCHAR2(2 BYTE) DEFAULT '0', 
	"SYNCED" VARCHAR2(2 BYTE) DEFAULT '0'
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" 
 LOB ("PHOTO") STORE AS SECUREFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
  STORAGE(INITIAL 106496 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
--------------------------------------------------------
--  DDL for Table T_LOGS
--------------------------------------------------------

  CREATE TABLE "ALPHA"."T_LOGS" 
   (	"ID" VARCHAR2(32 BYTE) DEFAULT sys_guid(), 
	"MESSAGE_CODE" NUMBER(8,0), 
	"BODY" CLOB, 
	"CREATED_DATE" DATE DEFAULT sysdate, 
	"TYPE" VARCHAR2(20 BYTE), 
	"PAIR_NO" VARCHAR2(32 BYTE), 
	"STATUS_CODE" NUMBER(4,0), 
	"USER_ID" NUMBER(20,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 0 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" 
 LOB ("BODY") STORE AS SECUREFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
  STORAGE(INITIAL 106496 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
--------------------------------------------------------
--  DDL for Table T_MESSAGES
--------------------------------------------------------

  CREATE TABLE "ALPHA"."T_MESSAGES" 
   (	"CODE" NUMBER(8,0), 
	"NAME" VARCHAR2(100 BYTE), 
	"BACKEND" VARCHAR2(100 BYTE), 
	"URL" VARCHAR2(500 BYTE), 
	"BODY_TEMPLATE" VARCHAR2(4000 BYTE), 
	"CREATED_DATE" DATE DEFAULT sysdate, 
	"METHOD" VARCHAR2(10 BYTE), 
	"IS_PROTECTED" CHAR(1 BYTE) DEFAULT 'N', 
	"IS_END" CHAR(1 BYTE) DEFAULT 'Y', 
	"SKIP_LOG" NUMBER DEFAULT 0, 
	"DELETED" VARCHAR2(2 BYTE) DEFAULT '0', 
	"SYNCED" VARCHAR2(2 BYTE) DEFAULT '0'
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 0 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table T_ORDER
--------------------------------------------------------

  CREATE TABLE "ALPHA"."T_ORDER" 
   (	"ID" VARCHAR2(32 BYTE) DEFAULT sys_guid(), 
	"OGNOO" VARCHAR2(32 BYTE) DEFAULT TO_CHAR(sysdate, 'YYYY-MM-DD HH24:MM:SS'), 
	"SHIREEID" VARCHAR2(32 BYTE), 
	"SHIREENAME" VARCHAR2(32 BYTE), 
	"HAANA" VARCHAR2(32 BYTE), 
	"USERID" VARCHAR2(32 BYTE), 
	"USERNAME" VARCHAR2(255 BYTE), 
	"PAIRID" VARCHAR2(32 BYTE), 
	"PRODUCTID" VARCHAR2(32 BYTE), 
	"PRODUCTNAME" VARCHAR2(32 BYTE), 
	"PRODUCTUNE" VARCHAR2(32 BYTE) DEFAULT 0, 
	"PRODUCTURTUG" VARCHAR2(32 BYTE) DEFAULT 0, 
	"ORDEREDDATE" VARCHAR2(32 BYTE), 
	"PRODUCTTOO" VARCHAR2(32 BYTE) DEFAULT 0, 
	"TOTALPRICE" VARCHAR2(32 BYTE), 
	"ZARSAN" VARCHAR2(32 BYTE) DEFAULT 'Зарсан', 
	"SYNCED" VARCHAR2(32 BYTE) DEFAULT '0', 
	"SYNCEDDATE" VARCHAR2(32 BYTE), 
	"LASTREACTIONDATE" VARCHAR2(32 BYTE) DEFAULT TO_CHAR(sysdate, 'YYYY-MM-DD HH24:MI:SS'), 
	"SHIREEPRICE" VARCHAR2(32 BYTE), 
	"UTGA" VARCHAR2(255 BYTE), 
	"DELETED" VARCHAR2(2 BYTE) DEFAULT '0'
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table T_PENDINGS
--------------------------------------------------------

  CREATE TABLE "ALPHA"."T_PENDINGS" 
   (	"PAIR_ID" VARCHAR2(32 BYTE), 
	"URL" VARCHAR2(500 BYTE), 
	"BODY" CLOB, 
	"STATUS" VARCHAR2(10 BYTE) DEFAULT 'PENDING', 
	"CREATED_DATE" DATE DEFAULT sysdate, 
	"UPDATED_DATE" DATE DEFAULT sysdate, 
	"RETRIES" NUMBER(4,0) DEFAULT 1, 
	"METHOD" VARCHAR2(10 BYTE), 
	"MESSAGE_CODE" NUMBER(8,0), 
	"USER_ID" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 0 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE( PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" 
 LOB ("BODY") STORE AS SECUREFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES ) ;
--------------------------------------------------------
--  DDL for Table T_PRODUCTBALANCE
--------------------------------------------------------

  CREATE GLOBAL TEMPORARY TABLE "ALPHA"."T_PRODUCTBALANCE" 
   (	"ID" VARCHAR2(32 BYTE), 
	"NAME" VARCHAR2(255 BYTE), 
	"PRICE" VARCHAR2(32 BYTE), 
	"PIECE" VARCHAR2(32 BYTE), 
	"TOTAL" VARCHAR2(32 BYTE), 
	"SRT" NUMBER
   ) ON COMMIT DELETE ROWS ;
--------------------------------------------------------
--  DDL for Table T_RESPONSE_MESSAGES
--------------------------------------------------------

  CREATE TABLE "ALPHA"."T_RESPONSE_MESSAGES" 
   (	"ID" NUMBER, 
	"LANGUAGE_CODE" VARCHAR2(20 BYTE), 
	"MESSAGE_CODE" VARCHAR2(100 BYTE), 
	"CONTENT" VARCHAR2(500 BYTE), 
	"CREATED_DATE" DATE DEFAULT sysdate, 
	"UPDATED_DATE" DATE DEFAULT sysdate, 
	"DELETED" VARCHAR2(2 BYTE) DEFAULT '0', 
	"SYNCED" VARCHAR2(2 BYTE) DEFAULT '0'
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 0 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table T_SHIREE
--------------------------------------------------------

  CREATE TABLE "ALPHA"."T_SHIREE" 
   (	"ID" VARCHAR2(32 BYTE) DEFAULT sys_guid(), 
	"NME" VARCHAR2(100 BYTE), 
	"NGJ" VARCHAR2(32 BYTE) DEFAULT 'pub', 
	"QRURL" VARCHAR2(255 BYTE) DEFAULT 'http://65.109.6.10/qrmenu/', 
	"QRID" VARCHAR2(32 BYTE) DEFAULT sys_guid(), 
	"STS" VARCHAR2(32 BYTE) DEFAULT 'Идэвхтэй', 
	"RNG" VARCHAR2(32 BYTE) DEFAULT '0', 
	"USR" VARCHAR2(32 BYTE), 
	"CDT" VARCHAR2(32 BYTE) DEFAULT TO_CHAR(sysdate, 'YYYY/MM/DD HH24:MI:SS'), 
	"SYNCED" VARCHAR2(32 BYTE) DEFAULT '0', 
	"DELETED" VARCHAR2(32 BYTE) DEFAULT '0'
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table T_TEMP
--------------------------------------------------------

  CREATE GLOBAL TEMPORARY TABLE "ALPHA"."T_TEMP" 
   (	"ID" VARCHAR2(255 BYTE)
   ) ON COMMIT DELETE ROWS ;
--------------------------------------------------------
--  DDL for Table T_USERS
--------------------------------------------------------

  CREATE TABLE "ALPHA"."T_USERS" 
   (	"ID" VARCHAR2(50 BYTE) DEFAULT sys_guid(), 
	"REG_NO" VARCHAR2(12 BYTE), 
	"FNM" VARCHAR2(100 BYTE), 
	"LNM" VARCHAR2(100 BYTE), 
	"FAMILY_NAME" VARCHAR2(100 BYTE), 
	"CIVIL_ID" VARCHAR2(20 BYTE), 
	"PHONE" VARCHAR2(8 BYTE), 
	"UNM" VARCHAR2(100 BYTE), 
	"BKD" VARCHAR2(20 BYTE), 
	"PASSCODE" VARCHAR2(2000 BYTE), 
	"BIRTH_DATE" DATE, 
	"GENDER" NUMBER(1,0), 
	"EMAIL" VARCHAR2(200 BYTE), 
	"ADDRESS" VARCHAR2(500 BYTE), 
	"AIMAG_CODE" VARCHAR2(4000 BYTE), 
	"SUM_CODE" VARCHAR2(2 BYTE), 
	"BAG_CODE" VARCHAR2(3 BYTE), 
	"ACCOUNT_NO" NUMBER(12,0), 
	"STATUS" CHAR(1 BYTE) DEFAULT 'A', 
	"C_LEVEL" NUMBER(2,0) DEFAULT 1, 
	"IS_CHILD" CHAR(1 BYTE) DEFAULT 'N', 
	"MOTHER_ID" VARCHAR2(20 BYTE), 
	"FATHER_ID" VARCHAR2(20 BYTE), 
	"DRIVE_EXP" NUMBER(2,0) DEFAULT 1, 
	"ZIPCODE" VARCHAR2(8 BYTE) DEFAULT '11000', 
	"AIMAG_ZIP" VARCHAR2(20 BYTE) DEFAULT '11000', 
	"SUM_ZIP" VARCHAR2(20 BYTE) DEFAULT '11000', 
	"CREATED_DATE" DATE DEFAULT sysdate, 
	"DRIVER_LICENSE_NUMBER" VARCHAR2(20 BYTE), 
	"PROFILE_IMAGE_URL" VARCHAR2(255 BYTE), 
	"DRIVER_LICENSE_NUMBER1" VARCHAR2(20 BYTE), 
	"IS_PIN" NUMBER DEFAULT 0, 
	"IS_PHONE_ACTIVATED" NUMBER DEFAULT 0, 
	"IS_EMAIL_ACTIVATED" NUMBER DEFAULT 0, 
	"COUNTRY_CODE" VARCHAR2(20 BYTE) DEFAULT 'MN', 
	"COUNTRY_NAME" VARCHAR2(255 BYTE) DEFAULT 'Монгол улс', 
	"CHECKID" VARCHAR2(1000 BYTE), 
	"RLE" VARCHAR2(4000 BYTE), 
	"SQD" VARCHAR2(32 BYTE), 
	"RNK" VARCHAR2(255 BYTE), 
	"STS" VARCHAR2(32 BYTE), 
	"PHT" VARCHAR2(255 BYTE), 
	"CDT" VARCHAR2(32 BYTE) DEFAULT TO_CHAR(sysdate, 'YYYY/MM/DD'), 
	"USR" VARCHAR2(32 BYTE), 
	"TOKEN" VARCHAR2(255 BYTE), 
	"EXPIREDATE" DATE, 
	"PASSWORD" VARCHAR2(2000 BYTE), 
	"NAME" VARCHAR2(255 BYTE), 
	"DELETED" VARCHAR2(2 BYTE) DEFAULT '0', 
	"SYNCED" VARCHAR2(2 BYTE) DEFAULT '0'
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
